print('Hola mundo')
print('Me encanta estudiar Python')
print('Estudiar con "Python Total" es super divertido')
print(1110 - 555)
print('1110 - 555')
print( "Hola" + ' Jesus')
print('Línea 1\nLínea 2\nLínea 3')